services:
  server:
    build:
      context: ./server
    command: npm run start
    volumes:
      - pitagoras-database:/app/database

  client:
    build:
      context: ./client
      args:
        - VITE_SERVER_HOST=http://localhost/api
    command: nginx -g 'daemon off;'
    depends_on:
      - server

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client

volumes:
  pitagoras-database: